service:
  type: web
  name: block
  runtime: python
  plan: free
  buildCommand: "pip install -r requirments.txt"
  startCommand: "gunicorn blog:.wsvg"
  envVars:
    key: PYTHON_VERSION
    value: 3.15.5
