service:
  type: web
  name: block
  runtime: python
  plan: free
  buildCommand: "pip install -r requirments.txt"
  startCommand: "gunicorn block.wsgi:application --workers 2 --bind 0.0.0.0:$PORT"
  envVars:
    key: PYTHON_VERSION
    value: 3.15.5
